import SettingsAside from './components/aside'

export const metadata = {
  title: 'Mentor Hub',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="flex pt-3 pb-6 gap-3 md:gap-6">
      <SettingsAside />
      {children}
    </div>
  )
}
