import SettingsAside from './components/aside'

export const metadata = {
  title: 'Mentor Hub',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="flex bg-gray-100 p-4">
      <SettingsAside />
      {children}
    </div>
  )
}
