import Navbar from '@/components/navbar'
import { AIChatbot } from '@/components/shared/ai-chatbot'
import 'stream-chat-react/dist/css/v2/index.css'

export const metadata = {
  title: 'Mentor Hub',
  description: 'Generated by Next.js',
}

export default function ProfileLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <main className="container mx-auto">
      <Navbar />
      {children}
      <AIChatbot />
    </main>
  )
}
