export const metadata = {
  title: 'Mentor Hub',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className="container mx-auto">
        {children}
      </body>
    </html>
  )
}
