import Providers from '@/providers'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

const cairo = localFont({
  src: [
    {
      path: '../public/fonts/Cairo-Regular.ttf',
      weight: '400',
      style: 'regular',
    },
    {
      path: '../public/fonts/Cairo-Medium.ttf',
      weight: '500',
      style: 'medium',
    },
    {
      path: '../public/fonts/Cairo-SemiBold.ttf',
      weight: '600',
      style: 'semiBold',
    },
    {
      path: '../public/fonts/Cairo-Bold.ttf',
      weight: '700',
      style: 'bold',
    },
  ],
  variable: '--font-cairo',
})

export const metadata: Metadata = {
  title: 'Mentor Hub',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${cairo.variable} antialiased container mx-auto`}
        suppressHydrationWarning>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
