import Navbar from '@/components/navbar'

export const metadata = {
  title: 'Mentor Hub',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <main className="container mx-auto">
      <Navbar />
      {children}
    </main>
  )
}
